#!/bin/bash
source _common.sh
source /usr/share/yunohost/helpers

get__pairing_code() {
    echo YNH_NULL
}

set__pairing_code() {
    if [[ -n "${pairing_code:-}" ]]; then
        [[ "$pairing_code" =~ ^[a-f0-9]{48}$ ]] || ynh_die "Le code d’appairage temporaire est invalide."
        ynh_app_setting_set --key=pairing_code --value="$pairing_code"
        ynh_app_setting_delete --key=gateway_key
    fi
}

run__apply_pairing() {
    bridge_apply
}

run__test_connection() {
    bridge_test
}

run__detach() {
    bridge_detach
}

ynh_app_config_run "$1"
